import Link from "next/link";

import { BrandMark } from "@/components/ui/icon";
import { Reveal } from "@/components/reveal";

const candidateBenefits = [
  ["Evidence, not claims", "Turn repositories and work samples into a profile employers can trust."],
  ["See your next step", "Get a clear view of the skills and proof that strengthen your story."],
  ["Keep ownership", "Build one living professional profile instead of rewriting every resume."]
];

const employerBenefits = [
  ["Understand capability faster", "See concrete evidence alongside the skills candidates say they have."],
  ["More confident shortlists", "Compare candidates with a consistent, structured view of their experience."],
  ["A more human signal", "Look beyond titles and keyword matching to discover real potential."]
];

function BenefitList({ items }: Readonly<{ items: string[][] }>) {
  return <div className="mt-8 grid gap-4 sm:grid-cols-3">{items.map(([title, body], index) => <Reveal key={title} delay={index * 100}><article className="h-full rounded-card border border-border bg-white/80 p-5 shadow-card"><span className="inline-flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-sm font-bold text-primary">0{index + 1}</span><h3 className="mt-5 text-base font-semibold text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-secondary">{body}</p></article></Reveal>)}</div>;
}

export function LandingPage({ sessionError }: Readonly<{ sessionError: boolean }>) {
  return (
    <main className="overflow-hidden">
      <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8">
        <Link href="/" className="flex items-center gap-3"><BrandMark /><span className="text-sm font-semibold tracking-wide text-ink">BeyondResume</span></Link>
        <nav className="hidden items-center gap-7 text-sm text-secondary md:flex" aria-label="Landing navigation"><a href="#how-it-works" className="hover:text-primary">How it works</a><a href="#for-candidates" className="hover:text-primary">For candidates</a><a href="#for-employers" className="hover:text-primary">For employers</a></nav>
        <Link href="/login" className="text-sm font-semibold text-primary hover:text-primary/80">Sign in</Link>
      </header>

      <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 pb-24 pt-12 sm:px-8 lg:grid-cols-[1fr_.95fr] lg:pb-32 lg:pt-20">
        <div className="absolute left-1/2 top-0 -z-10 h-96 w-96 -translate-x-1/2 rounded-full bg-indigo-300/20 blur-3xl" />
        <Reveal><p className="inline-flex rounded-full border border-primary/15 bg-primary/5 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.12em] text-primary">Professional proof, made visible</p><h1 className="mt-6 max-w-3xl text-5xl font-semibold tracking-[-.055em] text-ink sm:text-6xl lg:text-7xl">Show what you can do, <span className="text-primary">beyond</span> the resume.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-secondary">Build an evidence-based professional profile that helps employers understand your verified skills, experience, and potential.</p>{sessionError ? <p className="mt-4 text-sm text-danger" role="alert">We could not verify your session. Sign in to continue.</p> : null}<div className="mt-9 flex flex-wrap gap-3"><Link href="/register" className="inline-flex min-h-control items-center justify-center rounded-button bg-primary px-6 text-sm font-semibold text-white shadow-lg shadow-primary/25 transition hover:-translate-y-0.5 hover:bg-indigo-600">Create your profile</Link><Link href="/login" className="inline-flex min-h-control items-center justify-center rounded-button border border-border bg-white px-6 text-sm font-semibold text-ink transition hover:-translate-y-0.5 hover:shadow-md">Sign in</Link></div></Reveal>
        <Reveal delay={150} className="relative mx-auto w-full max-w-xl"><div className="absolute -inset-6 rounded-[2.5rem] bg-gradient-to-br from-indigo-300/30 to-cyan-200/30 blur-2xl" /><div className="relative rounded-[2rem] border border-white/80 bg-white/80 p-5 shadow-float backdrop-blur"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="h-11 w-11 rounded-2xl bg-gradient-to-br from-primary to-cyan-400" /><div><p className="font-semibold text-ink">Alex Morgan</p><p className="text-xs text-secondary">Frontend engineer</p></div></div><span className="rounded-full bg-success/10 px-3 py-1 text-xs font-semibold text-success">Verified</span></div><div className="mt-6 rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center justify-between text-xs text-slate-300"><span>Evidence profile</span><span>82% complete</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[82%] rounded-full bg-cyan-400" /></div><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs">React</span><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs">TypeScript</span><span className="rounded-lg bg-white/10 px-2.5 py-1 text-xs">Product thinking</span></div></div><div className="mt-4 grid grid-cols-2 gap-4"><div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs text-secondary">Work evidence</p><p className="mt-2 text-2xl font-semibold text-ink">24 <span className="text-sm font-medium text-success">+6</span></p></div><div className="rounded-2xl border border-border bg-white p-4"><p className="text-xs text-secondary">Skill passport</p><p className="mt-2 text-2xl font-semibold text-ink">18 <span className="text-sm font-medium text-primary">skills</span></p></div></div></div></Reveal>
      </section>

      <section id="how-it-works" className="border-y border-border/70 bg-white/55 py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><p className="text-sm font-semibold text-primary">HOW IT WORKS</p><h2 className="mt-3 text-3xl font-semibold tracking-tight text-ink sm:text-4xl">A clearer story in three steps.</h2></Reveal><div className="mt-12 grid gap-5 md:grid-cols-3">{[["Connect", "Bring your professional signals together in one place."], ["Build proof", "Create a living profile from skills, experience, and evidence."], ["Get discovered", "Give employers the context to recognize your potential."]].map(([title, body], index) => <Reveal key={title} delay={index * 110}><article className="rounded-card border border-border bg-surface p-6 shadow-card"><span className="text-sm font-semibold text-primary">0{index + 1}</span><h3 className="mt-12 text-xl font-semibold text-ink">{title}</h3><p className="mt-3 leading-7 text-secondary">{body}</p></article></Reveal>)}</div></div></section>
      <section id="for-candidates" className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><Reveal><p className="text-sm font-semibold text-primary">FOR CANDIDATES</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight text-ink sm:text-4xl">Let your work speak with more clarity.</h2></Reveal><BenefitList items={candidateBenefits} /></section>
      <section id="for-employers" className="bg-slate-950 py-24 text-white"><div className="mx-auto max-w-7xl px-5 sm:px-8"><Reveal><p className="text-sm font-semibold text-cyan-300">FOR EMPLOYERS</p><h2 className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight sm:text-4xl">Meet the person behind the application.</h2></Reveal><div className="mt-8 text-slate-300 [&_.text-ink]:text-white [&_.text-secondary]:text-slate-300 [&_.bg-white\/80]:bg-white/5 [&_.bg-primary\/10]:bg-cyan-300/10 [&_.text-primary]:text-cyan-300 [&_.border-border]:border-white/10"><BenefitList items={employerBenefits} /></div></div></section>
      <section className="mx-auto max-w-5xl px-5 py-24 text-center sm:px-8"><Reveal><div className="rounded-[2rem] bg-gradient-to-br from-primary to-indigo-700 px-6 py-16 shadow-float sm:px-12"><p className="text-sm font-semibold uppercase tracking-[.13em] text-indigo-200">Ready when you are</p><h2 className="mx-auto mt-4 max-w-2xl text-3xl font-semibold tracking-tight text-white sm:text-4xl">Build a profile that tells the fuller story.</h2><p className="mx-auto mt-4 max-w-xl leading-7 text-indigo-100">Your next opportunity deserves more than a list of keywords.</p><Link href="/register" className="mt-8 inline-flex min-h-control items-center rounded-button bg-white px-6 text-sm font-semibold text-primary transition hover:-translate-y-0.5 hover:shadow-lg">Get started</Link></div></Reveal></section>
      <footer className="border-t border-border bg-white/70"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-secondary sm:flex-row sm:items-center sm:justify-between sm:px-8"><div className="flex items-center gap-3"><BrandMark /><span className="font-semibold text-ink">BeyondResume</span></div><p>© {new Date().getFullYear()} BeyondResume. Make your work visible.</p></div></footer>
    </main>
  );
}
